//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TikanpoikaAdmin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tuote : IValidatableObject
    {
        public int TuoteID { get; set; }
        [Required]
        [StringLength(50)]
        public string Nimi { get; set; }
        [Required]
        [DisplayFormat(NullDisplayText = "tyhjä")]
        [Range(Double.Epsilon, Double.MaxValue, ErrorMessage ="Virhe")]
        public decimal Hinta { get; set; }
        [Required]
        [DisplayFormat(NullDisplayText = "tyhjä")]
        [Range(0, Double.MaxValue, ErrorMessage = "Virhe")]
        public decimal Veroprosentti { get; set; }

        IEnumerable<ValidationResult> IValidatableObject.Validate(
          ValidationContext validationContext)
        {
            if (Hinta < 0)
            {
                yield return new ValidationResult("Anna positiivinen desimaaliluku!");
            }

            if(Veroprosentti < 0)
            {
                yield return new ValidationResult("Veroprosentti ei voi olla negatiivinen!");
            }
        }

    }
}
